name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest-stable"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Resolve Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies \
            -project KMReader.xcodeproj \
            -scheme KMReader \
            -sdk iphonesimulator

      - name: Build iOS
        run: |
          xcodebuild clean build \
            -project KMReader.xcodeproj \
            -scheme KMReader \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -hideShellScriptEnvironment \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest-stable"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Resolve Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies \
            -project KMReader.xcodeproj \
            -scheme KMReader \
            -sdk macosx

      - name: Build macOS
        run: |
          xcodebuild clean build \
            -project KMReader.xcodeproj \
            -scheme KMReader \
            -sdk macosx \
            -destination 'platform=macOS' \
            -hideShellScriptEnvironment \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

  tvos:
    name: tvOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest-stable"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Resolve Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies \
            -project KMReader.xcodeproj \
            -scheme KMReader \
            -sdk appletvsimulator

      - name: Build tvOS
        run: |
          xcodebuild clean build \
            -project KMReader.xcodeproj \
            -scheme KMReader \
            -sdk appletvsimulator \
            -destination 'generic/platform=tvOS Simulator' \
            -hideShellScriptEnvironment \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
